### ISSUE TITLE
Validate EntityReferences with null logicalName on .Initialize()

### ISSUE THREAD

**Issue by jordimontana82** [DynamicsValue/fake-xrm-easy#107]
There might be the case that an entity reference is passed into the .Initialize() method without a logical name by mistake.

This will make the query execution crash when searching for the associated metadata of said entity references and it is a very confusing, not friendly error and it can be quite hard to troubleshoot.

So, this issue is a proposal to at least validate that every entity reference has a logical name set, and if not, throw an exception at that very moment, with a much more descriptive error message.

**Comment by BetimBeja** [comment]
```csharp
     private void ValidateEntityReferences(Entity e)
     {
         foreach (var item in e.Attributes)
         {
             if (item.Value is EntityReference entityReference && String.IsNullOrEmpty(entityReference.LogicalName))
             {
                 throw new Exception($"Broken EntityReference record during Initialize() for column '{item.Key}' of a '{e.LogicalName}' record.");
             }
         }
     }
```
