### ISSUE TITLE
Wrong ResponsibleType in CloseIncidentRequestExecutor

### ISSUE THREAD

**Issue by nsarris** [DynamicsValue/fake-xrm-easy#116]
There seems to be a slight oversight in CloseIncidentRequestExecutor, where the GetResponsibleRequestType method returns the typeof(CloseIncidentResponse) instead of typeof(CloseIncidentRequest) so the executor is never invoked.

Link to code:
https://github.com/DynamicsValue/fake-xrm-easy-messages/blame/83e99e56a4ea47a7e6ab7bce4eb77d1cfd150790/src/FakeXrmEasy.Messages/FakeMessageExecutors/CloseIncidentRequestExecutor.cs#L86

**Comment by jordimontana82** [comment]
Good catch @nsarris .

I'll add this to the next release.

**Comment by jordimontana82** [comment]
https://dynamicsvalue.github.io/fake-xrm-easy-docs/releases/2x/2.5.0/
