### ISSUE TITLE
Whether IXrmFakedContext  support ExportPdfDocument message

### ISSUE THREAD

**Issue by MuthuKumaran-Maniv** [DynamicsValue/fake-xrm-easy#125]
OrganizationRequest exportPdfAction = new OrganizationRequest("ExportPdfDocument");

 exportPdfAction["EntityTypeCode"] = entityTypeCode;
 exportPdfAction["SelectedTemplate"] = new EntityReference("documenttemplate", (Guid)wordTemplateId);
 exportPdfAction["SelectedRecords"] = "[\'{" + addNote.entityId + "}\']";

 OrganizationResponse convertPdfResponse = (OrganizationResponse)addNote.service.Execute(exportPdfAction);
I would like to know how to do the code coverage (unit test case) for the organization request to generate pdf using the FakeXRMEasy, please find the below error because even in the error its mention us to check in the github so kindly let us know some suggestions to resolve the below error.
**FakeXrmEasy.Abstractions.Exceptions.OpenSourceUnsupportedException: 'Exception occurred: The organization request type 'Microsoft.Xrm.Sdk.OrganizationRequest' is not yet supported..**

**Comment by jordimontana82** [comment]
@MuthuKumaran-Maniv  thanks a mill for your feedback.

This request is interesting, and it is not currently implemented in FXE so asking for feedback here.

It seems it used to be available, then locked down...  it seems you need a premium license.

This link now redirects (https://docs.microsoft.com/en-us/dynamics365/sales-enterprise/developer/exportpdf-api) to create quote pdf link below.

Are you using this api in the context of a Sales / Premium license? @MuthuKumaran-Maniv 

Background info: 

http://www.bwmodular.org/blog/real-time-pdf-generation-from-word-templates-in-dynamics-365 (credit to @bwmodular)
https://learn.microsoft.com/en-us/dynamics365/sales/create-quote-pdf 
https://experience.dynamics.com/ideas/idea/?ideaid=0c7f12cb-9a2a-ec11-b76a-0003ff45b7ab

**Comment by MuthuKumaran-Maniv** [comment]
@jordimontana82  Thanks for the suggestion actually we have implemented this pdf functionality and its working fine now we would like to know how to do the code coverage (unit test case) for the organization request to generate pdf using the FakeXRMEasy, please find the below error because even in the error its mention us to check in the github so kindly let us know some idea to resolve the below error.
**FakeXrmEasy.Abstractions.Exceptions.OpenSourceUnsupportedException: 'Exception occurred: The organization request type 'Microsoft.Xrm.Sdk.OrganizationRequest' is not yet supported.**.

**Comment by jordimontana82** [comment]
Thanks @MuthuKumaran-Maniv , that message has been already implemented but is not yet on nuget. It'll be published soon along with many other updates.

https://github.com/DynamicsValue/fake-xrm-easy-messages/blob/2x-dev/src/FakeXrmEasy.Messages/FakeMessageExecutors/GenericExecutors/ExportPdfDocumentExecutor.cs

Gentle reminder the new version FakeXrmEasy is offered under a triple license model. If you have a commercial subscription please reach out to us at https://dynamicsvalue.com/contact.

**Comment by jordimontana82** [comment]
Added to 2.5.0 https://dynamicsvalue.github.io/fake-xrm-easy-docs/releases/2x/2.5.0/

**Comment by MuthuKumaran-Maniv** [comment]
Thanks for the update @jordimontana82
