### ISSUE TITLE
One-to-many relationship metadata is not generated correctly.

### ISSUE THREAD

**Issue by Zerajima** [DynamicsValue/fake-xrm-easy#135]
Looking at MetadataGenerator.PopulateRelationshipProperty method I can see that One-to-many and Many-to-one relationships are not generated properly. In both cases ReferencedEntity/ReferencedAttribute and ReferencingEntity/ReferencingAttribute pairs are switched. 

When dataverse generates One-to-many relationship, ReferencedEntity represents "One" part of relationship and ReferencingEntity represents "many" side of relationship. So if we have a collection property, that represents One-to-many relationship, the type in which this property is located should be ReferencedEntity and the generic argument of collection should be ReferencingEntity.

**Comment by BetimBeja** [comment]
I will need to test this.
I thought I had unit tests to validate this at the time.

**Comment by BetimBeja** [comment]
hey, it is almost the 5-year anniversary of this change 🤣 
https://github.com/jordimontana82/fake-xrm-easy/pull/396

No tests for relationship metadata apparently

**Comment by jordimontana82** [comment]
@BetimBeja Yep! Time flies... almost the 10th anniversary of FXE! :smile:  I added some when it was needed for a PR to pass the quality gate https://github.com/DynamicsValue/fake-xrm-easy/issues/77

**Comment by jordimontana82** [comment]
This made it to 2.6 and 3.6 versions
