### ISSUE TITLE
Delete and DeleteRequest do not work for Late-Bound entities in Pipeline Simulation

### ISSUE THREAD

**Issue by clurdish** [DynamicsValue/fake-xrm-easy#144]
When using pipeline simulation, late-bound entities work most of the time. However, the framework skips looking for registered plugin steps for Delete requests. This includes both `IOrganizationService.Delete(..)` and `IOrganizationService.Execute(new DeleteRequest {...})`.

The following code appears to be where the issue lies.

https://github.com/DynamicsValue/fake-xrm-easy-plugins/blob/2x-dev/src/FakeXrmEasy.Plugins/IXrmFakedContextPipelineExtensions.cs#L459

Within `IXrmFakedContextPipelineExtensions.GetPluginStepsForOrganizationRequest`, the following code exists. Because the Delete request's target is of type `EntityReference`, the code looks for a reflected type matching the logical name of the target. Since only late-bound types are used here (i.e. `Entity`), it will never call `context.GetStepsForStage`. 

```csharp
//...
else if (target is EntityReference)
{
    var entityReference = target as EntityReference;
    var entityType = context.FindReflectedType(entityReference.LogicalName);
    if (entityType == null)
    {
        return null;
    }

    return context.GetStepsForStage(requestName, stage, mode, (Entity)Activator.CreateInstance(entityType));
}
//...
```

**Comment by jordimontana82** [comment]
@clurdish Fix done, it will be resolved in the next release

**Comment by jordimontana82** [comment]
@clurdish It's on nuget now, lots of other updates there too: https://dynamicsvalue.github.io/fake-xrm-easy-docs/releases/2x/2.5.0/
