### ISSUE TITLE
cannot  mock environment variables that used in plugins

### ISSUE THREAD

**Issue by Ram-Rockkzz** [DynamicsValue/fake-xrm-easy#156]
We have env variables to get some confi. We could not create a mocked entity for environment variables while unit testing with fake xrm and it is saying service doesnt have them. Suggest me some help on how to test

**Comment by jordimontana82** [comment]
Hi Ram,

It would be best if you could please provide some sample code to see how you are accessing these environment variables. If there a chance you could provide said sample please?

**Comment by SarviH** [comment]
I tried environment variables for Dynamics 365 and it's working pretty fine please let us know if it's the same case for you
here is my sample of creating environmentVariable in a testmethod

```
string jsonEnvironmentVariableVal = "[ { \"applicationUser\":\"test-testuser\", \"applicationUserId\":\"93a4a23f-3ae3-eb11-bacb-0022486d8624\" }]";

var environmentVariableValue = new Entity("environmentvariablevalue");

environmentVariableValue.Id = Guid.NewGuid();

environmentVariableValue.Attributes.Add("value", jsonEnvironmentVariableVal);

environmentVariableValue.Attributes.Add("environmentvariabledefinitionid", new EntityReference("environmentvariabledefinition", Guid.Parse("75cf97bf-daf6-eb11-bacb-000d3a09eec4")));

```
//Create environment variable value

`_service.Create(environmentVariableValue);`

 

//Create dump environment variable definition

```
var environmentVariableDefinition = new Entity("environmentvariabledefinition");

environmentVariableDefinition.Id = Guid.Parse("75cf97bf-daf6-eb11-bacb-000d3a09eec4");

environmentVariableDefinition.Attributes.Add("schemaname", "testSchemaName");

```
//Create environment variable

`_service.Create(environmentVariableDefinition);`

**Comment by jordimontana82** [comment]
Thanks a mill @SarviH  for your feedback. 

@Ram-Rockkzz  can you please elaborate on where you have issues? If @SarviH 's amples is not working for you please post a sample unit test that we can use to reproduce your particular scenario.

**Comment by Ram-Rockkzz** [comment]
Hi Team,Thank you so much for responding. It was my mistake that i havent added environment variables tables in early bind classes. It is working fine and as expected. Please apologise my late response. thanks and regardsP.RamireddyOn 30 Aug 2024, at 12:46 AM, Jordi ***@***.***> wrote:﻿
Thanks a mill @SarviH  for your feedback.
@Ram-Rockkzz  can you please elaborate on where you have issues? If @SarviH 's sample is not working for you please post a sample unit test that we can use to reproduce your particular scenario.

**Comment by jordimontana82** [comment]
Ok makes sense @Ram-Rockkzz  . Closing this issue so.
