### ISSUE TITLE
Deprecated libraries in 2.5.0

### ISSUE THREAD

**Issue by JoehannusApg** [DynamicsValue/fake-xrm-easy#170]
The nuget libraries Microsoft.IdentityModel.Clients.ActiveDirectory and Microsoft.Rest.ClientRuntime that are pulled when getting version 2.5.0 for  FakeXrmEasy from Nuget are deprecated.

**Comment by jordimontana82** [comment]
Hi @JoehannusApg 

These libraries are not directly referenced by FakeXrmEasy, they are transitive dependencies in the Microsoft.CrmSdk.* SDK nuget packages:

![image](https://github.com/user-attachments/assets/40f86763-28f0-4705-9c4e-c211028ec035)

![image](https://github.com/user-attachments/assets/4243f746-62bb-413d-b6e9-880ba75341f0)

I would suggest raising it with them (MSFT) to see if there are any plans to update them.

**Comment by JoehannusApg** [comment]
Hi Jordy. How the hell do you raise an issue with MSFT for this? I couldn't find a GitHub repo for this. And on nuget there's no way to do this either. During the year we are going to have to move to SonarCube. And we'll be getting these deprecated messages. And I'm not sure whether the department that manages SonarCube will allow us to add exceptions for this.

As I mentioned in another issue here posted by another developer I did find a post on community.dynamics.com where they advise you to migrate from Microsoft.CrmSdk.XrmTooling.CoreAssembly to the Dataverse ServiceClient. But I don't know whether that is an option for a unit test framework that is specifically meant for unit testing plugins. As for the development of plugins Microsoft still advises you to keep on using Microsoft.CrmSdk.CoreAssemblies.

**Comment by jordimontana82** [comment]
@JoehannusApg you might want to try an MSFT support ticket, or else the Contact Owner section of nuget.org.

With that said, there is a parallel issue where we're moving XrmTooling dependencies to a different package, that will mitigate the issue for unit testing (as most packages won't rely on XrmTooling), but will still persist for integration testing. 

I've just seen you replied to that issue so will continue from there... :)
