### ISSUE TITLE
Make dependencies less specific

### ISSUE THREAD

**Issue by BetimBeja** [DynamicsValue/fake-xrm-easy#21]
The FakeXrmEasy.Plugins.v365 should allow for `Microsoft.CrmSdk.CoreAssemblies` Versions `[8.2.0, 9)`
currently it is fixed to `8.2.0.1`
![image](https://user-images.githubusercontent.com/11160171/144721622-9b890891-cdf7-45c9-a81e-806ea2bd7256.png)

**Comment by jordimontana82** [comment]
We would need to update this across all 2x packages so tagging it accordingly. Thanks for raising this Betim.

**Comment by jordimontana82** [comment]
Hi Betim, this was pushed into versions 2.1.1 and 2.1.2 of the main package, if could try again?
