### ISSUE TITLE
Add GetDefaultPluginContext and ExecutePluginWith<T> methods to XrmRealContext

### ISSUE THREAD

**Issue by jordimontana82** [DynamicsValue/fake-xrm-easy#35]
This will allow to debug locally the code of plugins but using a connection to a real target environment.

- [x] Add functionality to the plugins package
- [x] Add similar functionality to the code activities package

**Comment by IvoBouwman** [comment]
Hi Jordi,
I was using this feature in v1 a lot.
Could you please include this issue in the next version?

**Comment by jordimontana82** [comment]
Thank @IvoBouwman 

Yes, indeed. It was supposed to be part of 2.2.0 but it wasn't. So will include it in the next one.

**Comment by jordimontana82** [comment]
Hi @IvoBouwman  

This is done. It'll be part of 2.3.0 release. 

The unit tests are so meta that XrmRealContext was unit tested with an XrmFakedContext! : D

https://github.com/DynamicsValue/fake-xrm-easy-plugins/blob/2x-dev/tests/FakeXrmEasy.Plugins.Tests/IXrmBaseContextPluginExtensions/XrmRealContextTests.cs#L17
