### ISSUE TITLE
Pipeline Simulation doesn't seem to work with late bound entities

### ISSUE THREAD

**Issue by jordimontana82** [DynamicsValue/fake-xrm-easy#38]

**Comment by clurdish** [comment]
@jordimontana82 Is there a possibility that plugin steps could be registered by logical name instead of object type code? That seems to be one of the major blockers here.

**Comment by jordimontana82** [comment]
@clurdish  It's an option indeed, the object type code is currently generated by crmsvcutil and also used in sdkmessageprocessingstep entity , but that's not part of the the out of the box Entity object in the SDK. In the other hand, even if using late bound, a custom entity (or any entity) does always have an object type code in the server. If we had to mimic a logic closer to that I would maybe also add the possibilty to specify object type codes for them or even generate them. (option b)

**Comment by clurdish** [comment]
@jordimontana82 Reading into the source further, it looks like currently the pipeline simulation is always trying to use reflection to determine the object type code (`EntityTypeCode`). Maybe there's an opportunity to lookup the object type code by logical name if that reflection check returns null, in which case we'd need to register the entity metadata.

My initial thought was to register the entity metadata using `IXrmFakedContext.SetEntityMetadata`, but it seems that the object type code for an entity is generated by the server and read-only for the `EntityMetadata` type. There are ways to override this using reflection, but probably something that would need at least an extension method to help usability.

I also considered extending `Entity` to allow a field `EntityTypeCode` to be set manually, but that has a couple issues. First, `IsSubclassOf` is invoked on the entity type to automatically turn on proxy types at present. Second, it seems duplicative to define _both_ the logical name and object type code when instantiating a late-bound entity.

From a test author's perspective, it'd be preferable to not have to explicitly define what an entity's object type code is; that is, first class support for late-bound entities. However, to more closely model how a real dataverse instance behaves, it could make sense to have a one-time upfront registration of the object type codes in the context "setup" - basically in the same place as the plugin steps are registered. I'm partial toward option A, but I'm not sure what other implications it has in terms of accurate simulation.

To answer your latter question - I'm using plain late bound entities.

**Comment by jordimontana82** [comment]
> I also considered extending Entity to allow a field EntityTypeCode to be set manually, but that has a couple issues. First, IsSubclassOf is invoked on the entity type to automatically turn on proxy types at present. Second, it seems duplicative to define both the logical name and object type code when instantiating a late-bound entity.

Agree on this bit.

The idea behind InitializeMetadata was to use it only if needed (i.e. when you need to test messages that do use metadata, i.e. RetrieveEntityRequest). 

My idea was something along the lines of , during the middleware setup, and indeed using reflection, to generate automatically an EntityTypeCode value for each entity if not using early bound entities .

In that way it wouldn't be redundant to the dev (no need to set it manually) either.

There is also some pipeline improvements coming where the registration would be even automatic based on attributes at the plugin class level.

That solution would fit nicely into the new improvements too.

Plus, reflection is getting even faster in .net 7 :)

**Comment by clurdish** [comment]
@jordimontana82 That sounds interesting - I'll look forward to more details! Let me know if I can help in any way. 

I have a client that is looking into commercial licensing for v2.x. They have very heavy usage of late-bound entities in virtually all plugin assemblies, and this would be a great asset for implementing plugin unit tests in such an environment.

**Comment by jordimontana82** [comment]
Awesome! Yeah feel free to ping me if you need some help :)

**Comment by jordimontana82** [comment]
@clurdish  This is done, it was merged as part of this PR: https://github.com/DynamicsValue/fake-xrm-easy-plugins/pull/16 and will make it to v2.2.0 version.

There is a new method signature that can be used for both late and early bound now. It simplifies also the quite excessive number of parameter there...

https://github.com/DynamicsValue/fake-xrm-easy-plugins/blob/2x-dev/src/FakeXrmEasy.Plugins/IXrmFakedContextPipelineExtensions.cs#L39-L44

Just not there yet on NuGet cause I'd like to include other features as well as small fixes too, and then, update the docs again :)

**Comment by jordimontana82** [comment]
@clurdish This is on nuget. I did a demo about it at the [bizzsummit.es](https://bizzsummit.es/) event last Saturday. The slides for the presentation are [here](https://github.com/DynamicsValue/bizzsummit-es-2022) . Will also record some videos and upload them to YouTube soon.

In the meantime, please feel free to check the [release notes](https://dynamicsvalue.github.io/fake-xrm-easy-docs/releases/2x/2.2.0/) and a [new code samples repo](https://github.com/DynamicsValue/fake-xrm-easy-samples)

**Comment by jordimontana82** [comment]
@clurdish Worth checking out how this area is evolving...

Custom Apis there now along with automatic registration:

https://dynamicsvalue.github.io/fake-xrm-easy-docs/releases/2x/2.3.0/
