### ISSUE TITLE
Github version not clear in LINQpad

### ISSUE THREAD

**Issue by bwmodular** [DynamicsValue/fake-xrm-easy#41]
Hi @jordimontana82,
a weird cosmetic issue in LINQPad. Don't really know if it's a LINQpad issue or a FXE issue.

With the v1 Nuget packages, it's possible in the LINQPad NuGet package manager to see which version of CRM the package references:
![image](https://user-images.githubusercontent.com/1889586/170735671-c626b8d6-d339-4744-bffb-0864493d14b2.png)
but with the v2/3 packages, it's no longer possible to distinguish them - they all look the same, so it's much harder to chose the right version - you have to select each version in turn in order to be able to see the ID value:
![image](https://user-images.githubusercontent.com/1889586/170736472-dfc635c5-8fc5-4359-b7b7-02a3489ba72b.png)

This isn't true in Visual Studio:
![image](https://user-images.githubusercontent.com/1889586/170735938-6ff612a3-34a4-4ffe-9e78-e49dcf385c98.png)

Was there some additional info in the NuGet manifest which LINQPad was previously using which is no longer there in v2/3?

Let me know if you need more info or if I can help testing this.

Thanks,
Ben

**Comment by jordimontana82** [comment]
Hi Ben,

I'll take a look at this. The package Id's are fine , on the screenshot at least they display the same package Id as in Nuget or VS. Maybe it's pulled from another property of the package and so we'll need to maybe review the build scripts. In v1 versions it was using a .nuspec file. In v2/v3 versions the package is built using dotnet pack directly from the .csproj properties.

**Comment by jordimontana82** [comment]
Maybe it's coming from the title property, I'll play a little bit with this:

    <Title>FakeXrmEasy Abstractions</Title>

**Comment by jordimontana82** [comment]
Hi @bwmodular ,

It seems the fix in the build script did the trick, so it'll be soon there....

![imagen](https://user-images.githubusercontent.com/3968950/170876445-d1a9a538-02fa-4806-b68e-82796d41f3a2.png)

**Comment by bwmodular** [comment]
Wonderful, thanks for looking into it - it will make life easier for us LINQPad users!

**Comment by jordimontana82** [comment]
Hi @bwmodular  

Could you try with latest versions of the v2 packages to see how the look like now?

**Comment by bwmodular** [comment]
@jordimontana82 Unfortunately, LINQPad displays the info from the latest version, which (for FakeXrmEasy core) it thinks is version 3.1.0 so it's displaying the info from the v3 version:
![image](https://user-images.githubusercontent.com/1889586/171002152-38cb268e-939d-4757-bdd5-48d3486dbb34.png)

I can see that there is a more recent version of v2 by selecting 'Add specific version to query' but the information about that version isn't visible in the main NuGet package selector.
![image](https://user-images.githubusercontent.com/1889586/171002464-1fa481a7-5aec-43b7-a0d8-fd6c6b8a8fb7.png)

So I think for the change to be visible, you need to update the v3 version.

**Comment by jordimontana82** [comment]
@bwmodular 3.1.1 out there now..... pls let me know if that looks fine, and if so, feel free to close this issue :)
