### ISSUE TITLE
Complex sub-query on link-entity fails

### ISSUE THREAD

**Issue by bwmodular** [DynamicsValue/fake-xrm-easy#63]
This might be a duplicate of this old issue from v1: https://github.com/jordimontana82/fake-xrm-easy/issues/584

Testing a query which would be written like this in SQL:

select * from salesOrder s,
            salesorderdetail d
where d.quantity is not null 
AND 
((d.productname = "A" AND d.description = "B") 
OR
(d.productname = "C" AND d.productnumber = "D"))

In other words it has a nested sub query against the link-entity, where 2 conditions must both be true OR 2 different conditions must both be true.

Here's how it would look in fetchXMLBuilder and it returns results for both of the OR conditions:
![image](https://user-images.githubusercontent.com/1889586/195826184-c10b33fd-88db-454b-be1b-22740aae51fc.png)

Here's the query:
```
QueryExpression query = new QueryExpression("salesorder");	
// link to salesorderdetail
LinkEntity query_salesorderdetail = query.AddLink("salesorderdetail", "salesorderid", "salesorderid");

// Quantity not null
query_salesorderdetail.LinkCriteria.AddCondition("quantity", ConditionOperator.NotNull);
	
// Add an 'Or' filter
FilterExpression OrFilter = new FilterExpression();
query_salesorderdetail.LinkCriteria.AddFilter(OrFilter);
OrFilter.FilterOperator = LogicalOperator.Or;
	
// Filter with two Ands - A and B
FilterExpression aAndBFilter = new FilterExpression();
aAndBFilter.AddCondition("productname", ConditionOperator.Equal, "A");
aAndBFilter.AddCondition("description", ConditionOperator.Equal, "B");
	
// Filter with two Ands - C and D
FilterExpression cAndDFilter = new FilterExpression();
cAndDFilter.AddCondition("productname", ConditionOperator.Equal, "C");
cAndDFilter.AddCondition("description", ConditionOperator.Equal, "D");

// Add the two and filters to the Or Filter
OrFilter.AddFilter(aAndBFilter);
OrFilter.AddFilter(cAndDFilter);

EntityCollection installers = service.RetrieveMultiple(query);
```

and here's my initialisation:
```
SalesOrder order = new SalesOrder() { Id = Guid.NewGuid() };

SalesOrderDetail detail1 = new SalesOrderDetail() { Id = Guid.NewGuid(), SalesOrderId = order.ToEntityReference()
	, Quantity = 1, ProductName = "A", Description = "B" };
SalesOrderDetail detail2 = new SalesOrderDetail() { Id = Guid.NewGuid(), SalesOrderId = order.ToEntityReference()
	, Quantity = 1, ProductName = "C", Description = "D" };

	_context.Initialize(new Entity[] { order, detail1, detail2 });
```

The query should return two records, but it returns none.

I can provide a Unit Test, but want to check if this is already a known issue before I do.

**Comment by jordimontana82** [comment]
Hi Ben,

Thank you again, that's interesting.

Maybe is behaving differently when the EntityName property is not specified in the filter (wild guess). I'll setup a unit test to reproduce

**Comment by bwmodular** [comment]
Bit more digging and simiplifed the tests a little.
The equivalent of this query fails:
```
select * from salesOrder s,
         salesorderdetail d
         where d.quantity is not null
         AND 
         (d.description = "A" OR d.productdescription = "B")
```
wheras the equivalent of this query works OK:
```
select * from salesOrder s,
         salesorderdetail d
         where d.description = "A" OR d.productdescription = "B"
```
So it's the nested Or within the And which seems to break things.
[Issue63.zip](https://github.com/DynamicsValue/fake-xrm-easy/files/9840800/Issue63.zip)
The attached Unit tests have the two queries, as FetchXML and as QueryExpressions - two working OK (without the nested filter) and two not.

**Comment by jordimontana82** [comment]
Hi @bwmodular 

Thanks a lot for all this info.

**Comment by temmyraharjo** [comment]
Hi @jordimontana82  and @bwmodular,

Based on Ben's unit tests, I think I might find out how to fix this.
On this one
[https://github.com/DynamicsValue/fake-xrm-easy-core/blob/4bf44e1a98e44dd90a65b398f8db6de60ccaca4c/src/FakeXrmEasy.Core/Query/FilterExpressionExtensions.cs#L60](Expression.Or(Expression.Constant(true), Expression.Constant(false)))

false || false = false. So to fix the issue, just need to make it true || false = true.
I ran from my side and there seems no error already (but might need Ben's help to test a more complex scenario 🤣):

![image](https://github.com/DynamicsValue/fake-xrm-easy/assets/8713243/e6677c23-10d5-428f-b700-c363a2c55df1)
