### ISSUE TITLE
Error when querying Money attribute using Integer value

### ISSUE THREAD

**Issue by bwmodular** [DynamicsValue/fake-xrm-easy#64]
When querying a Money attribute, this query is valid against a real CRM instance:

![image](https://user-images.githubusercontent.com/1889586/195832331-5a557c63-f4b2-4b32-97e9-ba98ba103d75.png)

Against FXE (v2/v9) it gives this error:
_The binary operator Equal is not defined for the types 'System.Decimal' and 'System.Int32'._

![image](https://user-images.githubusercontent.com/1889586/195832552-58adf538-730c-405b-88dd-f08982dd3a81.png)

Easy to fix in code by changing to
_query.Criteria.AddCondition("priceperunit", ConditionOperator.Equal, 1.0m);_
but just pointing out difference between 'real' behaviour and FXE behaviour.
Sorry if its already reported.

**Comment by jordimontana82** [comment]
Thanks for pointing it out Ben.

Yes, it also happens for strings and option set values. Worth revisiting.

**Comment by bwmodular** [comment]
Here's some tests for this one.
[Issue64.zip](https://github.com/DynamicsValue/fake-xrm-easy/files/9843912/Issue64.zip)
I tried adding this:
```
                if (attributeType == typeof(Money))
                {
                    if (value is int)
                    {
                        value = new Money(Convert.ToDecimal(value));
                        return GetAppropiateCastExpressionBasedOnInt(input);
                    }
                    else
                    {
                        return GetAppropiateCastExpressionBasedOnDecimal(input);
                    }                    
                } 
```
to the method GetAppropiateCastExpressionBasedOnAttributeTypeOrValue in class TypeCastExpressions, which fixes the immediate problem, but it then fails with Specified cast is not valid.
 at line 55 (list = linqQuery.ToList();) in the Execute method of RetrieveMultipleRequestExecutor and I couldn't work out how to fix that...

**Comment by jordimontana82** [comment]
https://dynamicsvalue.github.io/fake-xrm-easy-docs/releases/2x/2.5.0/
