### ISSUE TITLE
Change default TargetFrameworks on PowerShell scripts

### ISSUE THREAD

**Issue by BetimBeja** [DynamicsValue/fake-xrm-easy#7]
Hello @jordimontana82 ,
I have been "struggling" a little with building all the packages, and I think I found the issue 😄 basically the powershell scripts need to have `"all"` as a default value for `$targetFrameworks` so that it produces all the packages with all the necessary frameworks when building it locally.

https://github.com/DynamicsValue/fake-xrm-easy/blob/b4ac22ccebfc4769121b20b03648e76f2b5f7a90/build-configuration.ps1#L2
https://github.com/DynamicsValue/fake-xrm-easy/blob/b4ac22ccebfc4769121b20b03648e76f2b5f7a90/build.ps1#L2

https://github.com/DynamicsValue/fake-xrm-easy/blob/b4ac22ccebfc4769121b20b03648e76f2b5f7a90/pack-configuration.ps1#L3
https://github.com/DynamicsValue/fake-xrm-easy/blob/b4ac22ccebfc4769121b20b03648e76f2b5f7a90/pack.ps1#L3

https://github.com/DynamicsValue/fake-xrm-easy/blob/b4ac22ccebfc4769121b20b03648e76f2b5f7a90/build-push-local.ps1#L3

**Comment by jordimontana82** [comment]
Good point! I'll update the README :+1:

**Comment by jordimontana82** [comment]
Building section updated in README  @BetimBeja
