### ISSUE TITLE
Failed to Add Execution Mock or Fake Message Executor for Request that is not yet supported.

### ISSUE THREAD

**Issue by fhariyadi** [DynamicsValue/fake-xrm-easy#73]
Exception: The organization request type 'Microsoft.Crm.Sdk.Messages.CalculateRollupFieldRequest' is not yet supported.

We have tried to AddExecutionMock<T>() and AddFakeMessageExecutor<T>() to the MiddlewareBuilder but the exception is still thrown. 

We are on FakeXrmEasy v9 - 3.2.0.

        _context = MiddlewareBuilder
                .New()
                .AddCrud()
                .AddFakeMessageExecutors(Assembly.GetAssembly(typeof(AddListMembersListRequestExecutor)))
                .AddGenericFakeMessageExecutors(Assembly.GetAssembly(typeof(NavigateToNextEntityOrganizationRequestExecutor)))
                .AddExecutionMock<CalculateRollupFieldRequest>(CalculateRollupFieldRequestMock)
                .AddFakeMessageExecutor<CalculateRollupFieldRequest>(new FakeCalculateRollupFieldRequestExecutor())
                .UseCrud()
                .UseMessages()
                .SetLicense(FakeXrmEasyLicense.RPL_1_5)
                .Build();
                
        private OrganizationResponse CalculateRollupFieldRequestMock(OrganizationRequest req)
        {
            return new CalculateRollupFieldResponse { ResponseName = "Successful" };
        }

        private class FakeCalculateRollupFieldRequestExecutor : IFakeMessageExecutor
        {
            public bool CanExecute(OrganizationRequest request)
            {
                return true;
            }

            public OrganizationResponse Execute(OrganizationRequest request, IXrmFakedContext ctx)
            {
                return new CalculateRollupFieldResponse { ResponseName = "Successful" };
            }

            public Type GetResponsibleRequestType()
            {
                return typeof(CalculateRollupFieldRequest);
            }
        }

**Comment by jordimontana82** [comment]
I've tried setting this setup and it works fine for me, regardless if I use ExecutionMock, or AddFakeMessageExecutor, or both, either sync or async. 

Could you please post a sample unit test?

![imagen](https://user-images.githubusercontent.com/3968950/205751101-78a9bf7f-9f46-441f-ad39-db21eddd9902.png)

![imagen](https://user-images.githubusercontent.com/3968950/205751680-4345cde5-2405-485e-abef-908f766eeb9c.png)

**Comment by jordimontana82** [comment]
Hi @fhariyadi 

Just following up to see if you had any chance to look into this yet? Setting a sample unit list like above would help.

If you could also tell me which packages you have installed and target framework would be nice too, just in case.

**Comment by fhariyadi** [comment]
Hi @jordimontana82, I have just got a chance to investigate further based on your reply and figured out the issue was due to my library version. I was using Microsoft.PowerPlatform.Dataverse.Client v0.6.6. 

I figured out the FakeXrmEasy.Core.v9 is on Dataverse.Client v1.0.1+. It is now working fine once I have updated my Dataverse.Client to v1.0.1 or v1.0.4.

Thank you for jumping on this quickly.

**Comment by jordimontana82** [comment]
No worries, glad it's working now!
