### ISSUE TITLE
InvalidPluginExecutionException Exceptions not thrown in Pipeline Simulation

### ISSUE THREAD

**Issue by bwmodular** [DynamicsValue/fake-xrm-easy#85]
When testing a plugin using Pipeline Simulation, if the plugin throws an InvalidPluginExecutionException this is not caught in the test.

If I test the plugin itself using ExecutePluginWith, the exception is caught in the test, but if I perform a CRUD operation in which the plugin is invoked, the test reports a different exception (System.Reflection.TargetInvocationException) and error message ('Exception has been thrown by the target of an invocation.')

I will create a failing test to demonstrate the issue....

**Comment by bwmodular** [comment]
Here's a bit more detail before I upload the tests in case I'm not clear.

When a plugin throws an invalid plugin exception, I'd expect to be able to write a test like this, where I'm just performing the Create in order to trigger the plugin and the exception:
`Contact contact = new Contact() { Id = Guid.NewGuid() };
Action act = () => _service.Create(contact);
InvalidPluginExecutionException exception = Assert.Throws<InvalidPluginExecutionException>(act);
Assert.Equal(PluginWhichThrowsAnException.PluginExceptionMessage, exception.Message);`

but this test fails because the exception that gets thrown is actually a TargetInvocationException.

This test works though - so if I call the plugin directly it works:
`Action act = () => _context.ExecutePluginWith<PluginWhichThrowsAnException>(pluginExecutionContext);
InvalidPluginExecutionException exception = Assert.Throws<InvalidPluginExecutionException>(act);            
Assert.Equal(PluginWhichThrowsAnException.PluginExceptionMessage, exception.Message);`

**Comment by BetimBeja** [comment]
I have faced the same issue this Monday

**Comment by bwmodular** [comment]
I created this pull request in the samples project to demonstrate the issue:
https://github.com/DynamicsValue/fake-xrm-easy-samples/pull/6

**Comment by BetimBeja** [comment]
@jordimontana82 the exception is thrown here: 
https://github.com/DynamicsValue/fake-xrm-easy-plugins/blob/f1f2ce4993463f80da5b3b8543596228b77abb4c/src/FakeXrmEasy.Plugins/IXrmFakedContextPipelineExtensions.cs#L453
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/11160171/220428405-23d6629c-4174-4d64-bd72-ba197c11246e.png">

**Comment by jordimontana82** [comment]
@bwmodular  @BetimBeja 

This made it to this version: https://www.nuget.org/packages/FakeXrmEasy.Plugins.v9/2.3.2#release-body-tab
