### ISSUE TITLE
Does pipeline simulation work with anything other than CRUD messages? eg Associate?

### ISSUE THREAD

**Issue by bwmodular** [DynamicsValue/fake-xrm-easy#87]
I'm writing some tests against a plugin step registered against the Associate Message.
The tests are fine if I test the code using ExecutePluginWith, but if I create the association in my test using service.Associate, the code in question does not get fired.

I'm not sure if the Associate message is handled in pipeline simulation and I've just not set my testbase up correctly. Should the pipeline work with Associate and Disassociate registered steps?

**Comment by BetimBeja** [comment]
I think you should check your pipeline setup 😄 I did the following test:

![image](https://user-images.githubusercontent.com/11160171/218795153-1c8935c1-f468-4354-98f4-241beaebf269.png)

```csharp
    _context.RegisterPluginStep<AssociateValidationPlugin>(new PluginStepDefinition()
        {
            MessageName = "Associate",
            Stage = ProcessingStepStage.Preoperation
        });
```

**Comment by jordimontana82** [comment]
Thank you @bwmodular !

It should work yes, this was a bit of a limitation in v1 where it was limited to CRUD operations, but in v2 or later, with the new middleware architecture, it was "easier" to update it to accept any message.

So yeah, it should.

**Comment by bwmodular** [comment]
Thanks both - I'll post a sample test and we can maybe work out what I'm doing wrong :-)

**Comment by bwmodular** [comment]
In a project where other spkl registered plugin tests are working OK, I have added a plugin which is registered to fire on Associate, post-operation. When I call it using service.Associate, the plugin is never entered.
I added spkl registration in the same plugin class of a post operation on Create of Contact and the plugin code is entered when I call service.Create. So I think the spkl registration is OK (and the associate plugin works when deployed using spkl so I think the spkl syntax is good.

I'm using the same tests base class as in the FakeXrmEasy.AutomaticRegistrationWithSpkl sample project.
So, middleware registration like this:
`public FakeXrmEasyTestsBase()
        {
            _context = MiddlewareBuilder
                    .New()
                    .AddCrud()
                    .AddFakeMessageExecutors(Assembly.GetAssembly(typeof(Account)))
                    .AddPipelineSimulation(new PipelineOptions()
                    {
                        UsePluginStepAudit = true,
                        UseAutomaticPluginStepRegistration = true,
                        PluginAssemblies = new List<Assembly>()
    {
        Assembly.GetAssembly(typeof(Opportunity_PostOperationCreatePlugin))
    },
                        CustomPluginStepDiscoveryFunction = PluginStepDiscoveryFn
                    })
                    // Use* -> Defines pipeline sequence
                    .UsePipelineSimulation()
                    .UseCrud()
                    .UseMessages()
                    .SetLicense(FakeXrmEasyLicense.Commercial)
                    .Build();
            _service = _context.GetOrganizationService();
            _tracing = _context.GetTracingService();
        }`

and the same PluginStepDiscoveryFn as in the sample project.

I'll write a test in the spkl registration test project to see if I can get it working there....

**Comment by BetimBeja** [comment]
@jordimontana82 @bwmodular I think I found the issue, and a workaround. The issue is that unbound actions like `Associate` don't trigger if the `PluginStepDefinition.EntityLogicalName` is an empty string but only when it is null. The workaround is to transform the `ToPluginStepDefinition` as follows:

```csharp
  public static PluginStepDefinition ToPluginStepDefinition(this CrmPluginRegistrationAttribute attribute, Type pluginAssemblyType)
        {
            return new PluginStepDefinition()
            {
                PluginType = pluginAssemblyType.FullName,
                MessageName = attribute.Message,
                EntityLogicalName = string.IsNullOrEmpty(attribute.EntityLogicalName) ? null : attribute.EntityLogicalName,
                FilteringAttributes = attribute.FilteringAttributes.ToFilteringAttributesEnumerable(),
                Id = !string.IsNullOrEmpty(attribute.Id) ? new Guid(attribute.Id) : Guid.NewGuid(),
                Mode = attribute.ExecutionMode == ExecutionModeEnum.Synchronous ? ProcessingStepMode.Synchronous : ProcessingStepMode.Asynchronous,
                Rank = attribute.ExecutionOrder,
                Stage = (ProcessingStepStage) (int) attribute.Stage,
            };
        }
```

**Comment by jordimontana82** [comment]
Sounds right, I'll play with it and submit a fix soon

**Comment by jordimontana82** [comment]
It works with null value though (dunno if that will make spkl crash)

This one was picked up

    [CrmPluginRegistration(
        MessageNameEnum.Associate, 
        null, 
        StageEnum.PreOperation, 
        ExecutionModeEnum.Synchronous,
        "", "PreCreate Associate",
        1, IsolationModeEnum.Sandbox
    )]

This one wasn't , but it works with Betim's solution.

    [CrmPluginRegistration(
        MessageNameEnum.Associate, 
        "", 
        StageEnum.PreOperation, 
        ExecutionModeEnum.Synchronous,
        "", "PreCreate Associate",
        1, IsolationModeEnum.Sandbox
    )]

Pushed some sample code with that fix and steps to reproduce (which was fairly easy with the new Plugin Step Auditing capability actually! ) :)

**Comment by bwmodular** [comment]
Ah, thanks both.
In this case, the EntityLogicalName is not null, but it is "none" which spkl seems happy with as an attribute value for Associate:
`entityLogicalName: "none",`
I've changed it to 
`entityLogicalName: null,`
and amended my ToPluginStepDefinition method as suggested by @BetimBeja and all working good now!

I'll add something to my ToPluginStepDefinition which deals with "none" later...

Thanks so much both of you.

**Comment by bwmodular** [comment]
Bit more feedback on this.
spkl doesn't actually like 
`entityLogicalName: null,`, throwing this error 'Warning: Cannot register step Associate on Entity'.
It expects the entityLogicalName to be like this where no entity is specified:
`entityLogicalName: "none",`
so that line in ToPluginStepDefinition needs to look more this:
`EntityLogicalName = (string.IsNullOrEmpty(attribute.EntityLogicalName) || attribute.EntityLogicalName == "none") ? null : attribute.EntityLogicalName,`
