### ISSUE TITLE
FakeXrmEasy allows creation of activity which is regarding to invalid entity reference.

### ISSUE THREAD

**Issue by fhariyadi** [DynamicsValue/fake-xrm-easy#88]
FakeXrmEasy.Core.v9  Version=2.3.0

Issues: when using FakeXrmEasy IOrganizationService we can create email which has RegardingObjectId set to EntityReference with valid entity logical name but invalid ID (record does not exists). This is not consistent behaviour with Dynamics IOrganizationService. 

In the following example, the _regardingObject_ is set to new EntityReference({VALID_CUSTOM_ENTITY_SCHEMA_NAME}, {GUID_OF _RECORD_WHICH_DOES_NOT_EXIST}. In this case, FakeXrmEasy service create operation does not throw an error and return the newly created email id. 

```
var fromParty = new ActivityParty
{
	PartyId = new EntityReference(Queue.EntityLogicalName, queueId)
};
var toParty = new ActivityParty { AddressUsed = recipientEmailAddress };

var newEmail = new Email
{
	Subject = messageSubject,
	Description = messageBody,
	RegardingObjectId = regardingObject,
	To = new[] { toParty },
	From = new[] { fromParty }
};

var emailId = service.Create(newEmail);
```

**Comment by BetimBeja** [comment]
Hi @fhariyadi,
When you set-up the middleware there is a property called `IntegrityOptions`. The default contains the `ValidateEntityReferences` property set to false. You can configure that option to true and the behavior will become consistent.

The default is configured like this...
```csharp
   _context.SetProperty<IIntegrityOptions>(new IntegrityOptions() {  ValidateEntityReferences = false });
```

**Comment by jordimontana82** [comment]
Thank you Felix, this is exactly like Betim suggested. It was a validation introduced later on as an optional feature.

**Comment by BetimBeja** [comment]
@jordimontana82 should this issue be closed?

**Comment by jordimontana82** [comment]
Yep, worth updating the docs with these details too.
