### ISSUE TITLE
ConditionOperator.In should not accept an array of integers as an argument

### ISSUE THREAD

**Issue by bwmodular** [DynamicsValue/fake-xrm-easy#96]
A trivial bug but it caught a colleague out recently, so worth reporting.
When using the 'In' ConditionOperator, passing an array as an argument like this:
`query.Criteria.AddCondition("statuscode", ConditionOperator.In, new int[] { 0,1 });` 
should cause an exception to be thrown but FakeXrmEasy does not complain about this syntax.

Here's what happens against a real Dynamics instance:
![image](https://user-images.githubusercontent.com/1889586/235308785-1dd5b882-afc1-463a-b038-d312a595192d.png)
Changing the syntax to this fixes the problem:
`query.Criteria.AddCondition("statuscode", ConditionOperator.In, 0, 1);`

Here's a test which demonstrates the issue:
public class IssueX : FakeXrmEasyTestsBase
 {
        [Fact]
        public void Using_The_In_ConditionOperator_With_An_Array_Should_Cause_An_Exception_To_Be_Thrown()
        {
            QueryExpression query = new QueryExpression("account") { TopCount = 10 };
            query.Criteria.AddCondition("statuscode", ConditionOperator.In, new int[] { 0,1 });
            Action act = () => _service.RetrieveMultiple(query);
            FaultException exception = Assert.Throws<FaultException>(act);
            Assert.Equal("Condition for attribute 'account.statuscode': expected argument(s) of type 'System.Int32' but received 'System.Int32[]'.", exception.Message);
        }
}

**Comment by jordimontana82** [comment]
Thanks a mill Ben for reporting it.
